services:
  - type: web
    name: movie-villa-backend
    runtime: docker
    plan: free
    region: oregon
    rootDir: backend
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /api/genres/
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: "*"
      - key: FRONTEND_HOST
        fromService:
          type: web
          name: movie-villa-frontend
          property: host

  - type: web
    name: movie-villa-frontend
    runtime: docker
    plan: free
    region: oregon
    rootDir: frontend
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: BACKEND_SCHEME
        value: https
      - key: BACKEND_URL
        fromService:
          type: web
          name: movie-villa-backend
          property: host
